# Generated by Django 4.0.6 on 2023-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
